name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    # Matrix of multiple Turbo jobs
    strategy:
      matrix:
        turbo:
          - lint
          - typecheck
          - build
          - test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: ${{ matrix.turbo }}
        run: pnpm turbo run ${{ matrix.turbo }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      
      - name: Upload source maps
        if: matrix.turbo == 'build'
        uses: matbour/setup-sentry-cli@v2
        with:
          token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          project: trizum-pwa
          organization: horusdev

      - name: Upload source maps
        if: matrix.turbo == 'build'
        shell: bash
        working-directory: packages/pwa
        run: |
          # Get full version
          pwa_version=$(cat package.json | jq -r '.version')
          last_commit=$(git rev-parse --short HEAD)
          full_version="${pwa_version}-${last_commit}"
          
          # Prepare sourcemaps
          sentry-cli sourcemaps inject ./dist/client

          # Upload sourcemaps
          sentry-cli sourcemaps upload --release $full_version ./dist/client

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [check]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run update-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  autofix:
    name: Autofix & Extract Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Autofix
        id: autofix
        run: pnpm lint:fix
        continue-on-error: true

      - name: Extract Messages
        id: extract-messages
        run: pnpm lingui:extract
        continue-on-error: true

      - uses: EndBug/add-and-commit@v9
        with:
          commit: --signoff
          add: --all
          message: "style: apply automatic fixes"
          committer_name: GitHub Actions
          committer_email: actions@github.com

      - name: Check if autofix and extract messages were successful
        if: ${{ steps.autofix.result != '0' || steps.extract-messages.result != '0' }}
        run: echo "::error::Autofix or extract messages failed" && exit 1
