name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    # Matrix of multiple Turbo jobs
    strategy:
      matrix:
        turbo:
          - lint
          - typecheck
          - build
          - test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: ${{ matrix.turbo }}
        run: pnpm turbo run ${{ matrix.turbo }}

  extract-messages:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20bfa68d879ec57187f2c5bf616158433763f05f06
          cache: "pnpm"
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Extract Messages
        continue-on-error: true
        run: pnpm lingui:extract

      - uses: EndBug/add-and-commit@v9
        with:
          commit: --signoff
          add: "--all"
          message: "i18n: update locales"
          committer_name: GitHub Actions
          committer_email: actions@github.com

  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20bfa68d879ec57187f2c5bf616158433763f05f06
          cache: "pnpm"
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Autofix
        continue-on-error: true
        run: pnpm lint:fix

      - uses: EndBug/add-and-commit@v9
        with:
          commit: --signoff
          add: --all
          message: "style: apply automatic fixes"
          committer_name: GitHub Actions
          committer_email: actions@github.com
