name: Syncpack

on:
  # Run whenever a pull request is updated
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  syncpack:
    name: Syncpack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - uses: JamieMason/syncpack-github-action@0.2.3
        with:
          package-manager: pnpm
          package-manager-version: "9.6.0"
          format-mismatches: ignore
          lockfile-mismatches: ignore
          semver-range-mismatches: lint
          version-mismatches: lint
          syncpack-version: "12.3.3"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
